name: CI Pipeline

on:
  push:
    branches: [ main ] # Run CI on pushes to the main branch
  pull_request:
    branches: [ main ] # Run CI on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 # Action to checkout the repository code
    
    - name: Set up Node.js
      uses: actions/setup-node@v2 # Action to set up Node.js environment
      with:
        node-version: '14' # Choose the appropriate Node.js version
    
    - name: Install Dependencies
      run: npm install # Command to install project dependencies
    
    - name: Run Unit Tests
      run: npm test # Command to run unit tests
    
