name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Car_rental_app\requirements.txt
      
      # Add more CI steps here (linting, testing, etc.)

  cd:
    runs-on: windows-latest
    needs: ci
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If requirements.txt is in a different folder, adjust the path accordingly:
          # pip install -r path/to/requirements.txt
      
      # Add deployment steps here (building, deploying, etc.)
