name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository's code
      with:
        fetch-depth: 0  # Fetch all history for accurate sonarcloud analysis

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: 3.x  # Use Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest  # Run your tests

    - name: Deploy to production
      if: success()  # Deploy only if tests are successful
      run: |
        # Assuming you have deployment commands here

